### ISSUE TITLE
URLs beginning with www.

### ISSUE THREAD

**Issue by siaron** [micronaut-projects/micronaut-multitenancy#73]
https://github.com/micronaut-projects/micronaut-multitenancy/blob/cb0c8a72da7543574ba2a4cc10e7d6969c7b504c/multitenancy/src/main/java/io/micronaut/multitenancy/tenantresolver/SubdomainTenantResolver.java#L52
- What will be the tenant resolved here if it starts with www.

**Comment by sdelamo** [comment]
We should use the [`HttpHostResolver`](https://github.com/micronaut-projects/micronaut-core/blob/4.1.x/http-server/src/main/java/io/micronaut/http/server/util/HttpHostResolver.java)
